### ISSUE TITLE
Error Origination

### ISSUE THREAD

**Issue by TLusti** [OpenWealth/OpenWealth#100]
Martin de Urgoiti (ZKB):

In the error context of the Custody API it is at times difficult for the TPP to identify  where the error has occurred which leads to longer resolution times. From the perspective of bLink it should be clear where the error has originated.

As the technical error ranges are fixed and cannot be changed, we would like to be able to indicate where the error has occured.

**Comment by martuOW** [comment]
Should this point be addressed within a SIX tech work group, as I could imagine that the other bLink interfaces would face the same issue. If it is a non-issue in general for the TPP, then I am happy to cancel/reject the issue.

**Comment by TLusti** [comment]
In my opinion, this should rather be addressed by SFTI, as bLink as well as OpenWealth are relying on the Common Error Responses provided by SFTI. If these Common Error responses are getting adjusted, bLink and OpenWealth then adapt these changes.
