### ISSUE TITLE
Properties unter "reuquired" sind anders benannt als unter "properties" (principalAmount vs notionalAmount, value vs amount)

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#105]
Im CreditDefaultSwap und TotalReturnSwap und InterestRateSwap steht bei required: - principalAmount aber in den properties - notionalAmount
Das sollte wohl der gleiche Begriff sein.

https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/TotalReturnSwap.yaml#L4

https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/CreditDefaultSwap.yaml#L4

https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/InterestRateSwap.yaml#L4

bei required: steht "value" und bei properties steht: "amount" im CurrencyAmount
https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Types/CurrencyAmount.yaml#L5

**Comment by andiahlm** [comment]
@FabianRuti Danke für den Hinweis!
