### ISSUE TITLE
FinancialInstrument Option - strikePrice/exercisePrice

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#107]
1- strikePrice gehört meiner Meinung nach zum underlying, daher fände ich es besser, dieses innerhalb der underlyingFinancialInstrument Struktur zu platzieren.
2 - warum hat es noch einen exercisePrice ? was ist der Unterschied zum strikePrice

https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/Option.yaml#L16

**Comment by andiahlm** [comment]
exercisePrice and strikePrice designate the same -> will be merged
strikePrice will still be on instruments properties, underlyingInstrument should only be a reference to underlying instruments (in line with reference standards such as ISO (MT, MX))
