### ISSUE TITLE
underlyingFinancialInstruments - weniger Details als in v1

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#108]
In der aktuellen Version unserer Umsetzung geben wir Underlyings immer mit, wenn in unserer Datenbasis vorhanden.

Neu in v3 gibt es underlyingFinancialInstrument soweit ich sehe nur bei Option, Future, CDS, TRS.
Wir haben aber auch bei anderen Instrumenttypen (z.b. Bonds, Anrechte, Strukturierte Produkten) Underlyings.

Beispiele für solche Fälle:
- Convertible Bonds
- Tracker Zertifikate (z.b auf Index)
- Bezugsrechte auf Aktien

In der jetzigen Version des YAML würde das bedeuten, dass wir in der v3 weniger Infos zu Underlyings liefern werden. Spezifisch für alle Instrumenttypen, die nicht Option, Future, CDS, TRS sind fehlen dann neu die Underlyings. Ist das so gewollt?

https://github.com/OpenWealth/OpenWealth/blob/bfd2e9292ac996d48e79712cba51d7affbe32435/CustodyServices/Specs/Resources/FinancialInstruments/Bond.yaml#L3

**Comment by andiahlm** [comment]
We will add underlying instrument property on 'bonds' and 'others'

**Comment by andiahlm** [comment]
> In der aktuellen Version unserer Umsetzung geben wir Underlyings immer mit, wenn in unserer Datenbasis vorhanden.
> 
> Neu in v3 gibt es underlyingFinancialInstrument soweit ich sehe nur bei Option, Future, CDS, TRS. Wir haben aber auch bei anderen Instrumenttypen (z.b. Bonds, Anrechte, Strukturierte Produkten) Underlyings.
> 
> Beispiele für solche Fälle:
> 
> * Convertible Bonds
> * Tracker Zertifikate (z.b auf Index)
> * Bezugsrechte auf Aktien
> 
> In der jetzigen Version des YAML würde das bedeuten, dass wir in der v3 weniger Infos zu Underlyings liefern werden. Spezifisch für alle Instrumenttypen, die nicht Option, Future, CDS, TRS sind fehlen dann neu die Underlyings. Ist das so gewollt?
> 
> https://github.com/OpenWealth/OpenWealth/blob/bfd2e9292ac996d48e79712cba51d7affbe32435/CustodyServices/Specs/Resources/FinancialInstruments/Bond.yaml#L3

@FabianRuti underlying ist auf dem other model jetzt vorhanden. Zusätzlich werden Tracker, Warrants, Kaptalschutz etc explizit unter strukturierten Produkten modelliert sein in der nächsten major version
