### ISSUE TITLE
Missing Data for required Fields in FinancialInstrument

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#109]
Quite a few properties are "required" in certain financialInstrumentTypes (e.g. option, bonds). Due to data quality or certain exotic variations it can happen that certain data points are missing. How should we handle such situations?

Options:
1. classify as "other"
2. send a placeholder in the missing property

https://github.com/OpenWealth/OpenWealth/blob/bfd2e9292ac996d48e79712cba51d7affbe32435/CustodyServices/Specs/Resources/FinancialInstruments/Option.yaml#L7

**Comment by andiahlm** [comment]
We will reduce the number of 'required' fields to a 'likely to be able to provide' from a providers perspective

**Comment by FabianRuti** [comment]
https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/Mortgage.yaml#L1

Bei Hypotheken und Darlehen haben wir leider jeweils den Zinssatz nicht, weil wir das etwas anders modelliert haben. Darum wären wir glücklich, wenn interest hier nicht required wäre (gleich wie bei Credit bereits jetzt)

**Comment by andiahlm** [comment]
> https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Resources/FinancialInstruments/Mortgage.yaml#L1
> 
> Bei Hypotheken und Darlehen haben wir leider jeweils den Zinssatz nicht, weil wir das etwas anders modelliert haben. Darum wären wir glücklich, wenn interest hier nicht required wäre (gleich wie bei Credit bereits jetzt)

@FabianRuti Habe ich so schon aufgenommen und das required field entfernt
