### ISSUE TITLE
Order Placement - Min and max items on accounts list 

### ISSUE THREAD

**Issue by chiny123** [OpenWealth/OpenWealth#112]
**Submitted by: Dmitry Ustyushkin - SQ
date: Dmitry Ustyushkin - SQ
Priority: n/a
T-shirt Size: M**

As the current allocation accounts list expects maximum two accounts and minimum one to be set, it would probably make sense to register this expectation and set max and min items  in the list

Version: OpenWealthAPI-OrderPlacement-2.0.7.yaml

**ZKB**: Just one alone is wrong, thus there must be two. Would it be better just to insist on two fixed entries instead of making it a list?
Check with Issue #25 & #27

**Comment by TLusti** [comment]
After discussions in a breakout group on FX, @chiny123 outlined, that for ZKB for FX trades even three account need to be provided (1x Container - i.e. SafekeepingAccount, and two cashAccounts). 
SQ on the other hand needs just one overall account that incorporates all the cash positions

**Comment by TLusti** [comment]
Closed as per discussion https://github.com/OpenWealth/OpenWealth/issues/149
