### ISSUE TITLE
Order Placement - “other” Accounts

### ISSUE THREAD

**Issue by chiny123** [OpenWealth/OpenWealth#113]
**Submitted by: Fabian Rutishauser - ZKB
Date: 20.12.2022**

Why is there a list with also “other” for the current scope it is sufficient to just have one cash Account and one Safekeeping Account.

Comment: 
Other was meant for special accounts. :question_mark:Can be used for cases where there is no distinction between account and safekeepingaccount.

- [x] Dmitry: Please review impact

**Comment by TLusti** [comment]
As per this discussion, all types still are needed. https://github.com/OpenWealth/OpenWealth/issues/149
