### ISSUE TITLE
Order Placement - Status Model Backward

### ISSUE THREAD

**Issue by chiny123** [OpenWealth/OpenWealth#116]
**Submitted by: Fabian Rutishauser
Date: n/a**

Due to manual interference sthe status of an order can go back. I.e. after changing a limit or trigger price of a partially filled order, it goes back to “placed”. The status model does not allow this. How shall do you approach such situations?

**SGKB**: We currently do not further process such trades but inform the EAM to submit the modified order again.

**Comment by TLusti** [comment]
Current understanding is, that as mentioned by SGKB, that such trades need to be resubmitted (DELETE --> POST)
