### ISSUE TITLE
Required field "value" gibt es nicht im Type Valuation

### ISSUE THREAD

**Issue by FabianRuti** [OpenWealth/OpenWealth#125]
Was ist hier required? Value gibt es nicht, nur valueInPositionCurrency und valueInReferenceCurrency. Wenn dann sollte es wohl valueInPositionCurrency  sein.

https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Types/Valuation.yaml#L5

**Comment by FabianRuti** [comment]
https://github.com/OpenWealth/OpenWealth/blob/d198f31f1c4d59742fde5e17eed17526dbabe31f/CustodyServices/Specs/Types/CurrencyAmount.yaml#L5

Gleiches für CurrencyAmount

**Comment by andiahlm** [comment]
@FabianRuti vielen Dank für die Hinweise, werden wir umgehen korrigieren
