### ISSUE TITLE
creditDebitIndicator no longer exists

### ISSUE THREAD

**Issue by SaraMeyer1** [OpenWealth/OpenWealth#127]
https://github.com/OpenWealth/OpenWealth/blob/17173c8f428cb2e4b57699163841076d24710e3c/CustodyServices/Specs/Types/CreditDebitIndicator.yaml#L1

**Comment by andiahlm** [comment]
@SaraMeyer1 thanks for noticing, will be remove

**Comment by TLusti** [comment]
@andiahlm was this handled in the latest release?
