### ISSUE TITLE
financial instrument type structured products

### ISSUE THREAD

**Issue by MichaelWuestSGKB** [OpenWealth/OpenWealth#130]
https://github.com/OpenWealth/OpenWealth/blob/de9e2aeecf2829665da26fff15e66c8d2ab8af1a/CustodyServices/Docs/FinancialInstrumentTypes.md?plain=1#L3-L28

To which financial instrument type do we attribute structured products? Should there be an additional financial instrument type for these assets?

**Comment by andiahlm** [comment]
@MichaelWuestSGKB In the current version the structured products should be classified under 'Others'. We have it on the roadmap for v4 to add and model the structured product in detail.

**Comment by MichaelWuestSGKB** [comment]
@andiahlm Great, thank you for the clarification.
