### ISSUE TITLE
financial instrument type ETFs

### ISSUE THREAD

**Issue by MichaelWuestSGKB** [OpenWealth/OpenWealth#131]
https://github.com/OpenWealth/OpenWealth/blob/de9e2aeecf2829665da26fff15e66c8d2ab8af1a/CustodyServices/Docs/FinancialInstrumentTypes.md?plain=1#L9-L10

It should be defined to which financial instrument type we attribute ETFs. It might be sufficient to add an example transaction here on Github or add this somewhere in the descriptions.

**Comment by andiahlm** [comment]
@MichaelWuestSGKB would it be feasible for you to add it to the funds? This was the initial thought. Are there any particular properties that would be missing in this case?
For a detailed Classification of the ETF the appropriate CFI code should be used.

**Comment by MichaelWuestSGKB** [comment]
@andiahlm The attributes of funds should be sufficient. For us it is important that all banks handle this assets similarly. That is why we proposed to add either an example of an ETF or mention ETFs specifically in the description of the FinancialInstrumentType funds.
