### ISSUE TITLE
Update MovementTypes

### ISSUE THREAD

**Issue by MichaelWuestSGKB** [OpenWealth/OpenWealth#133]
https://github.com/OpenWealth/OpenWealth/blob/de9e2aeecf2829665da26fff15e66c8d2ab8af1a/CustodyServices/Docs/TransactionAndMovementTypes.md?plain=1#L85-L106

Update MovementTypes with current specification: 
        - accruedInterest
        - additionalWithholdingTax
        - asset
        - brokerageFee
        - capitalGainTax
        - cash
        - commission (what is the purpose of this MovementType?)
        - custodyFee
        - exchangeFee
        - financialTransactionTax
        - interest
        - managementFee
        - otherFee
        - other
        - otherTax
        - premium
        - reclaimableTax
        - reinvestmentAmount
        - stampDuty
        - thirdPartyFee
        - transactionFee
        - valueAddedTax
        - withholdingTax

**Comment by andiahlm** [comment]
@MichaelWuestSGKB Der Update der Doku wird in folgendem branch abgewickelt und wird demnächst gemerged:

https://github.com/OpenWealth/OpenWealth/blob/improve-custody-services-documentation/CustodyServices/Docs/TypesAndImplementationGuideline.md

Offene Punkte sind notiert

**Comment by MichaelWuestSGKB** [comment]
Besten Dank.
