### ISSUE TITLE
Order placement / FX : allocation accounts format

### ISSUE THREAD

**Issue by dustyush0sq** [OpenWealth/OpenWealth#149]
As raised during FX / Crypto workgroup meeting, we would need  to agree on a way to specify  accounts in requested allocations for FX orders

To my understanding, ZKB would like to be able to specify multiple cash accounts

 

![image](https://github.com/user-attachments/assets/57980886-99ba-4a13-a768-c2f93b4c88b0)

**Comment by TLusti** [comment]
I see it the same way. This would not need any change to the current setup/specification on the requestedAllocationList.accounts. 
@chiny123 If ok with you, I would close this issue.

**Comment by chiny123** [comment]
Hi @TLusti , thanks, fine with me. this issue can be closed
