### ISSUE TITLE
Order Placement - Missing free text Instructions

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#23]
**Requestor:**
Fabian Rutishauser - ZKB

**Submission date:**
20.12.2022

**Priority Requestor:**
Medium

**Priority Community:**

**Effort T-Shirt Size:**
M

**Description:**
Include a Free Text field for handling instructions on top of the existing 10 standard instructions.

**Comment & Responsibility:**
Is possible to cover 95% of the instructions with an enumerated list of instruction reasons to avoid a free text field?

Example: For Eurex Options, the client must indicate if it’s using algos or not. Therefore, it should be looked into.

→ has to be discussed

**Comment by chiny123** [comment]
- how to avoid CID in the freetext fields?
- consider algo trading, iceberg orders.

**Comment by MichaelWuestSGKB** [comment]
We spoke about this topic with some of our traders. We would need handling instructions for the following cases:

1. **Fund orders with references:** EAMs often have special agreements with certain fund managers (e.g. pricing, subscriptions to restricted fund tranches). For this purpose, the trade has to be submitted including a reference. Often, this reference is the name of the EAM or an alphanumeric value. 
2. **New issues of products:** For newly issued products (e.g. structured products or warrants), we sometimes need additional information, e.g. about the settlement party or the price of the product. However, in many cases the assets are not yet opened in the core banking system of the bank. Implementing banks will probably have to tackle this issue individually.
3. **Trading instructions:** The most important trading instructions for our EAMs are the following: 
- Volume + percentage
- VWAP + length of time
- TWAP + length of time
- Spread over the day VWAP 
- Spread over the day TWAP 
- Iceberg + amount
- At Trader’s Discretion (Best Effort)
- _Other_

E.g. Credit Suisse currently offers the following trading instructions in their E-Banking:
- 5-10% of volume (Patient)
- 10-20% of volume (Neutral)
- 20-30% of volume (Agressive)
- Spread over the day (Target VWAP)
- Market on close (MOC)
- Hidden Size (Reserve)
- At Trader’s Discretion (Best Effort)
- 5% of volume
- 10% of volume
- 15% of volume
- 20% of volume
- 25% of volume
- 30% of volume
- VWAP 15 Minutes
- VWAP 30 Minuten
- VWAP 1 Hour
- VWAP 2 Hours
- VWAP excl. Opening/Closing
- VWAP excl. Opening
- VWAP excl. Closing
- Other (only Exceptions)

**Comment by TLusti** [comment]
With the release of OP 2.2.1 - free text instructions were added to the bulkOrderDetails as an optional field. 
This discussion can be taken up again, if there is the need to push that towards an enumerated value. 


https://github.com/OpenWealth/OpenWealth/blob/12a29751d28605859f0e5163df0547a1b23eb7e4/OrderPlacement/Specs/orderPlacementAPI-bundled.yaml#L680-L684
