### ISSUE TITLE
Order Placement - Pagination in  “all orders“ endpoint

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#45]
**Requestor:**
Dmitry Ustyushkin - SQ

**Submission date:**
10.05.2023

**Priority Community:**
Low

**Effort T-Shirt Size:**
M

**Description:**
Should there be an ordering defined for orders within pages being fetched ?  For example, by placement date or by last update date ? As the pagination mechanism with cursor implictly means the data set behind is ordered, would it make sense to state this in spceification ? Or rather to let each implementer decide ? 

_Version: OpenWealthAPI-OrderPlacement-2.0.7.yaml_

**Comment & Responsibility:**
Paging already possible in v2.0.7
Check if sorting default is needed

**Comment by TLusti** [comment]
Paging already possible in v2.0.7
