### ISSUE TITLE
Order Placement - Health check endpoint for order placement API

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#50]
**Requestor:**
Order Placement Circle

**Submission date:**
23.08.2023

**Priority Requestor:**
N/A

**Effort T-Shirt Size:**
M

**Description:**
Check the idea if the Order placement API specification should include a health check / heart beat endpoint.

**Comment & Responsibility:**
TL: Might be a topic that is overarching for all OW APIs. Nonetheless, the Order Placement API could be the defining group, as I see the highest necessity here. 

SQ: Might make sense with in FIX context with TCP, where the connection needs to stay open. For http this might not make sense.

**Comment by TLusti** [comment]
Might make sense with in FIX context with TCP, where the connection needs to stay open. For http this might not make sense.
