### ISSUE TITLE
Order Placement - Allocation status

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#61]
**Requestor:**
Circle

**Submission date:**
15.11.2023

**Priority Community:**
Medium

**Effort T-Shirt Size:**
N/A

**Description:**
Today the Service User will receive a notification “partially filled” → “partially filled” when an allocation has been done. The meaning is not explicit as it could simply mean a partial fill during the day.

We need to rediscuss on how to handle the (partial) allocations in the light of status notifications.

**Comment by TLusti** [comment]
This should be covered with the introduction of the last execution attribute in the notifications

**Comment by TLusti** [comment]
Status handled on Order level

Allocation.executedQuantity gives an indication on the "fill-level" per allocation
