### ISSUE TITLE
Order Placement - Implicit Subscription on Order

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#65]
**Requestor:**
Martin de Urgoiti - ZKB

**Submission date:**
04.12.2023

**Priority Community:**
Medium

**Effort T-Shirt Size:**
L

**Description:**
Rather than using the subscription mechanism of the event notification endpoint, it should be possible to indicate in the order for which status transitions you would like to receive status pushes (in the same consent).

**Comment & Responsibility:**
TL: I would rather separate the notification as far as possible from the API parts that can also be used without the notification functionality.

**Comment by TLusti** [comment]
not best practice
