### ISSUE TITLE
Order Placement - Notification recovery

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#66]
**Requestor:**
Pierre Planche

**Submission date:**
06.12.2023

**Priority Community:**
N/A

**Effort T-Shirt Size:**
N/A

**Description:**
There might be the need for a TPP to be able to continue the notifications from a certain ID (even if the bank in the meantime has sent more notifications after this one)

**Comment by TLusti** [comment]
if aggregated polling is introduced, this should be covered

**Comment by TLusti** [comment]
Aggregated Polling was introduced with V2.2 of the OP API and issue can be closed.
