### ISSUE TITLE
Order Placement - additional attribute for Order Routing

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#69]
**Requestor:**
JB

**Submission date:**
01.02.2024

**Priority Community:**
N/A

**Effort T-Shirt Size:**
N/A

**Description:**
Für das Routing des Orders wäre ein weiteres Attribut hilfreich (Z.B. Primär-/Sekundarmarkt/IPO/NIB)

**Comment by TLusti** [comment]
Duplicate
