### ISSUE TITLE
.vscode folder not needed

### ISSUE THREAD

**Issue by TLusti** [OpenWealth/OpenWealth#7]
Is the following folder really needed or was this uploaded by incident? 

$https://github.com/OpenWealth/OpenWealth/tree/main/.vscode

![image](https://github.com/OpenWealth/OpenWealth/assets/64965441/228ac9c0-1f33-494d-8d61-d4ce769cf416)

**Comment by andiahlm** [comment]
removed folder and added to gitignore and pushed immediatle
