### ISSUE TITLE
Order Placement - Introduction of HTTP Error 422 - Unprocessable Content

### ISSUE THREAD

**Issue by TLusti** [OpenWealth/OpenWealth#72]
As for the order placement, certain ways of placing an order might not be fully supported by all implementing parties, e.g. timeInForce - FillOrKill, an appropriate error should be introduced. 

The best fitting error response would be HTTP 422 - Unprocessable Content [https://datatracker.ietf.org/doc/html/rfc9110#name-422-unprocessable-content](url)

**Comment by MichaelWuestSGKB** [comment]
For the case you mentioned above, we currently use orderCancellationReasons. The respective orderCancellationReasons would be "selectedTimeInForceNotImplemented". Does this substitute the currently used implementation? Or are there other cases that are not yet covered in the orderCancellationReasons?

**Comment by TLusti** [comment]
Your current discribed approach seems to be sufficient for now.
