### ISSUE TITLE
Order Placement - Add possibility to restart the sending of notifications

### ISSUE THREAD

**Issue by TLusti** [OpenWealth/OpenWealth#73]
If a notification receiving party is experiencing an issue with their server and are not able to receive any notifications, there should be a way to trigger the sending of notifications again after fixing the issue. 

This might be done with a new endpoint, where a notificationId or timestamp can be provided, from which notification the notification should be sent again.

**Comment by martuOW** [comment]
A) The delivery of notifications is not guaranteed.
B) In such case the aggregated polling endpoint should suffice.

Thus my suggestion is to reject this issue.

**Comment by chiny123** [comment]
agree with Martin, in such case the user can also check the current status with GET/orders, as only the lasted order status might be interesting for the user

**Comment by TLusti** [comment]
With the addition of the aggregated polling, this issue can be omitted
