### ISSUE TITLE
Order Placement - DateTime fields unstructured

### ISSUE THREAD

**Issue by MichaelStaehli** [OpenWealth/OpenWealth#76]
**Requestor:**
Martin de Urgoiti - ZKB

**Submission date:**
23.10.2023

**Priority Community:**
N/A

**Effort T-Shirt Size:**
N/A

**Description:**
Due to an error in the SIX business flow simulator we discovered that dateTime fields are handled inefficiently. Our standard requires a string, however, internally we are using a serialised form, e.g.

“…DateTime" : {
    "year" : 2023,
    "month" : 10,
    "day" : 19,
    "hour" : 11,
    "minute" : 4,
    "second" : 54,
    "fractionalSecond" : 0.579525,
    "timeZoneOffsetMinutes" : 120,
    "future" : false,
    "past" : true,
    "millisecond" : 579,
    "microsecond" : 579525,
    "nanosecond" : 579525000

At the end of SIX the DateTime string is again serialised into fields.

The question to the community is whether we should deliver these fields instead of a string to simplify matters. This potentially also impact the Custody API.

At SIX: CONOP-654 for the date-format discussion and improved error-handling of invalid format

**Comment by TLusti** [comment]
I would not venture into picking a date-time format apart, if there is already a preexisting format that covers this.
