### ISSUE TITLE
Custody Services - Renaming numbersOfDaysAccrued proposal

### ISSUE THREAD

**Issue by TLusti** [OpenWealth/OpenWealth#8]
https://github.com/OpenWealth/OpenWealth/blob/f83e2893e52ccdae3f461823c0f52e4042001587/CustodyServices/Specs/Resources/position.yaml#L56

Proposal to rename `numberOfDaysAccrued` with `dayCountFactor` 

Because the factor would bear more information then the numbersOfDaysAccrued

See https://en.wikipedia.org/wiki/Day_count_convention

**Comment by andiahlm** [comment]
@TLusti are banks capable of sending it that way? I only know the numberOfDaysAccrued from ISO15022

**Comment by TLusti** [comment]
@andiahlm Would have to check with the banks.
