### ISSUE TITLE
Custody V3: yml file for FxForward can be removed

### ISSUE THREAD

**Issue by samynomad** [OpenWealth/OpenWealth#96]
https://github.com/OpenWealth/OpenWealth/blob/main/CustodyServices/Specs/Resources/FinancialInstruments/FxOption.yaml

File is no longer used an can be removed. At least, the FxOption is not listed as FinancialIstrument Type. 
Probably a remainder after a renaming?

**Comment by andiahlm** [comment]
@samynomad FxOption was required for this version and will be added to the enum and discriminator. This was still a mistake. Thanks for noticing!
